export const data: any[] = [
  { 
    id: 0,
    amount: '62,323,000', 
    username: '김앤장현',
    cheerUp: 4542,
    inShort: '전두환 나쁜넘 ㅜㅜ 디저라',
    comments: [
      { id: 0, username: '안녕나는', text: '와 님아 진짜 대단해요' },
      { id: 1, username: '어제까진', text: '감탄중입니다 ㅜㅜ' },
      { id: 2, username: '메시닷', text: '감사드려요' },
      { id: 3, username: '어서오세요', text: '댓글합니다.' },
      { id: 4, username: '김치국마시지마', text: '감바래!' },
      { id: 10, username: '안녕나는', text: '와 님아 진짜 대단해요' },
      { id: 11, username: '어제까진', text: '감탄중입니다 ㅜㅜ' },
      { id: 12, username: '메시닷', text: '감사드려요' },
      { id: 13, username: '어서오세요', text: '댓글합니다.' },
      { id: 14, username: '김치국마시지마', text: '감바래!' },
      { id: 20, username: '안녕나는', text: '와 님아 진짜 대단해요' },
      { id: 21, username: '어제까진', text: '감탄중입니다 ㅜㅜ' },
      { id: 22, username: '메시닷', text: '감사드려요' },
      { id: 23, username: '어서오세요', text: '댓글합니다.' },
      { id: 24, username: '김치국마시지마', text: '감바래!' },
      { id: 30, username: '안녕나는', text: '와 님아 진짜 대단해요' },
      { id: 31, username: '어제까진', text: '감탄중입니다 ㅜㅜ' },
      { id: 43, username: '어서오세요', text: '댓글합니다.' },
      { id: 44, username: '김치국마시지마', text: '감바래!' },
      { id: 50, username: '안녕나는', text: '와 님아 진짜 대단해요' },
      { id: 51, username: '어제까진', text: '감탄중입니다 ㅜㅜ' },
      { id: 52, username: '메시닷', text: '감사드려요' },
      { id: 53, username: '어서오세요', text: '댓글합니다.' },
      { id: 54, username: '김치국마시지마', text: '감바래!' },
      { id: 60, username: '안녕나는', text: '와 님아 진짜 대단해요' },
      { id: 61, username: '어제까진', text: '감탄중입니다 ㅜㅜ' },
      { id: 62, username: '메시닷', text: '감사드려요' },
      { id: 63, username: '어서오세요', text: '댓글합니다.' },
      { id: 64, username: '김치국마시지마', text: '감바래!' },
      { id: 70, username: '안녕나는', text: '와 님아 진짜 대단해요' },
      { id: 71, username: '어제까진', text: '감탄중입니다 ㅜㅜ' },
      { id: 72, username: '메시닷', text: '감사드려요' },
      { id: 73, username: '어서오세요', text: '댓글합니다.' },
      { id: 74, username: '김치국마시지마', text: '감바래!' },
      { id: 80, username: '안녕나는', text: '와 님아 진짜 대단해요' },
      { id: 81, username: '어제까진', text: '감탄중입니다 ㅜㅜ' },
      { id: 82, username: '메시닷', text: '감사드려요' },
      { id: 83, username: '어서오세요', text: '댓글합니다.' },
      { id: 84, username: '김치국마시지마', text: '감바래!' },
      { id: 90, username: '안녕나는', text: '와 님아 진짜 대단해요' },
      { id: 91, username: '어제까진', text: '감탄중입니다 ㅜㅜ' },
      { id: 92, username: '메시닷', text: '감사드려요' },
      { id: 93, username: '어서오세요', text: '댓글합니다.' },
      { id: 94, username: '김치국마시지마', text: '감바래!' },
    ],
  },
  { 
    id: 1,
    amount: '52,323,000', 
    username: '오늘도너를',
    cheerUp: 1542,
    inShort: '전두환 꼭 죽어서 벌받기를...',
    comments: [
      { id: 0, username: '오늘밤너를', text: '일단 집어넣었으니까 본격적으로 사자방, 댓글지시, 민간사찰 시작합시다!!' },
      { id: 1, username: '그리운미켈', text: '차고 넘친다는 뜻 .. 앞으로 재판 많이' },
      { id: 2, username: '지구거주민', text: '잘하는건 아니지 애초에 올리질 말았어야지' },
      { id: 3, username: '전국우르곳협회', text: '무지라는 이유로 잘못이 아니게 되는건 아니니' },
      { id: 4, username: '조스바러버', text: '다른 분야는 아예 듣을 생각도 안하는데' },
    ],
  },
  { 
    id: 2,
    amount: '42,323,000', 
    username: '안녕하세요',
    cheerUp: 2452,
    inShort: '광주민주화 운동... 잊지 맙시다...',
    comments: [
      { id: 0, username: '자존감e바닥', text: '왜이렇게 대부분 부정적인 댓글 밖에 없지? ' },
      { id: 1, username: '텐딸라', text: '몰랐다는건 용서할수 있고 이해할수 있는거 아닌가? 특히 다른 나라의 역사라면 더욱더' },
      { id: 2, username: '만딩고', text: '오히려 저렇게 수정하고, 사과하는걸 칭찬해주고 고마워 해야하는거 아닌가.. 저렇게 함으로써 많은 사람들도 배울수있고' },
      { id: 3, username: '너흰아직', text: '도대체 뭐가 고맙니 공식 계정으로 실수 저지르는건 공식계정으로 사과해야하는게 정식 아니겠니' },
      { id: 4, username: '자동완성봇', text: '만 긍정적인 댓글도 존나 보이는거임? 부정적인 댓글은 그럴만한 짓을 했으니깐 달리는거고' },
    ],
  },
  { 
    id: 3,
    amount: '32,323,000', 
    username: '김베르다입니다',
    cheerUp: 542,
    inShort: '노태우도 가만 두어서는 안됩니다.',
    comments: [
      { id: 0, username: '에펨코리아햄', text: '이거 쓰러 들어왔는데 미리 썼네 십새끼들 미리 생각 좀 하고 포스팅하지' },
      { id: 1, username: '펨코으른', text: '이래야지 더많은 사람들이 뭐가 문제인지, 왜 문제인지 알지' },
      { id: 2, username: 'poe', text: '도 이생각함 걍 계속 이런실수 했으면 좋겠음. 특히 이' },
      { id: 3, username: '닉네임은없음', text: '그리고 우리나라 사람들도 보이런던 안 입었으면 좋겠고. "보이런던 나치 독수리' },
      { id: 4, username: '칭찬맨', text: '도 아니고 리그단위로 저딴 짓을 할 수가 있다는게 어이가 없다..' },
    ],
  },
  { 
    id: 4,
    amount: '22,323,000', 
    username: '라이징오',
    cheerUp: 42,
    inShort: '대한민국의 정의를 살리기 위해서는 꼭 전두환을 처벌해야 합니다.',
    comments: [
      { id: 0, username: '타이거', text: '그래도 사과하잖아 바로인정하구 저게 어디냐' },
      { id: 1, username: '파크라이', text: '서양국가는 잘모를수있다본다 중요한건 잘못된걸 알고도 사과하냐 생까냐' },
      { id: 2, username: '가갸갸갸고교', text: '운전중이긴한데 폰 세워두고 말로 해서 찍은거 시속 한 15키로?' },
      { id: 3, username: '친사회적인격장애', text: '싫험ㅇㄹㅇ중' },
      { id: 4, username: '같이걷자', text: '안전운전하세요' },
    ],
  },
  { 
    id: 5,
    amount: '12,323,000', 
    username: '나는전설이다',
    inShort: '광주민주화만 있는것이 아닙니다.',
    cheerUp: 452,
    comments: [
      { id: 0, username: '짱희찬짱', text: '고생하시네' },
      { id: 1, username: '준섭섭해', text: '존나 웨스트브룩닮았네 저짤은' },
      { id: 2, username: '골든타임', text: '라인업 오지네 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { id: 3, username: '호세마우라', text: '고경표는 걔 아닌가 응답하라1988 덕선이 누나랑 사귀던 남자에 아니었나' },
      { id: 4, username: '나는백곰', text: '블랙넛이나 빨던 애가 빈지노 지디랑 친해졌네ㅋㅋ' },
      { id: 13, username: '호세마우라', text: '고경표는 걔 아닌가 응답하라1988 덕선이 누나랑 사귀던 남자에 아니었나' },
      { id: 14, username: '나는백곰', text: '블랙넛이나 빨던 애가 빈지노 지디랑 친해졌네ㅋㅋ' },
    ],
  },
];