const data = [
  {
    likes: 123,
    title: '北 "서로 분주하니 미루자"…북미회담 연기제안 배경 주목(종합)',
    commentCount: 32,
    writer: '오늘도너를',
    views: 3123,
    date: '11-08',
  },
  {
    likes: 3,
    title: '양진호 회장이 직원들에 BB탄을 난사했던 개조된 가스 리볼버',
    commentCount: 32,
    writer: '오늘도너를',
    views: 3123,
    date: '11-08',
  },
  {
    likes: 773,
    title: '"이상한 지정석" 광주 아파트 지하주차장 독점 논란',
    commentCount: 32,
    writer: '오늘도너를',
    views: 3123,
    date: '11-08',
  },
  {
    likes: 223,
    title: '[뉴스pick] "아이에게 비소를…후속조치 알려달라" BCG 백신 논란에 높아진 분노fdsfsdfdsffdgfdgdfgdfg',
    commentCount: 32,
    writer: '오늘도너를',
    views: 3123,
    date: '11-08',
  },
  {
    likes: 23,
    title: '10년 3357억원도 차버린 야구선수, 브라이스 하퍼',
    commentCount: 32,
    writer: '오늘도너를',
    views: 3123,
    date: '11-08',
  },
  {
    likes: 83,
    title: '4차전 우천취소, 역대 가장 늦은 KS 가능성 높아져',
    commentCount: 32,
    writer: '오늘도너를',
    views: 3123,
    date: '11-08',
  },
  {
    likes: 153,
    title: '한대화 감독관 우취 결정 이유 "비 예보 有, 해 안 떠 정비 쉽지 않다" [KS4]',
    commentCount: 32,
    writer: '오늘도너를',
    views: 3123,
    date: '11-08',
  },
  {
    likes: 63,
    title: '여호와의 증인은 "양심적 납세 거부"도 가능할까?',
    commentCount: 32,
    writer: '오늘도너를',
    views: 3123,
    date: '11-08',
  },
  {
    likes: 2,
    title: '2층 열린 문으로 찾아온 "불청객"…카페·패스트푸드점 "속앓이"',
    commentCount: 32,
    writer: '오늘도너를',
    views: 3123,
    date: '11-08',
  },
  {
    likes: 1,
    title: '정부 "LPG차 사용제한 폐지"…일반인 구매 길 열린다',
    commentCount: 32,
    writer: '오늘도너를',
    views: 3123,
    date: '11-08',
  },
  {
    likes: 123,
    title: '얼굴 합성한 신분증으로 토익 대리 시험',
    commentCount: 32,
    writer: '오늘도너를',
    views: 3123,
    date: '11-08',
  },
  {
    likes: 773,
    title: '"이상한 지정석" 광주 아파트 지하주차장 독점 논란',
    commentCount: 32,
    writer: '오늘도너를',
    views: 3123,
    date: '11-08',
  },
  {
    likes: 223,
    title: '[뉴스pick] "아이에게 비소를…후속조치 알려달라" BCG 백신 논란에 높아진 분노fdsfsdfdsffdgfdgdfgdfg',
    commentCount: 32,
    writer: '오늘도너를',
    views: 3123,
    date: '11-08',
  },
  {
    likes: 23,
    title: '10년 3357억원도 차버린 야구선수, 브라이스 하퍼',
    commentCount: 32,
    writer: '오늘도너를',
    views: 3123,
    date: '11-08',
  },
  {
    likes: 83,
    title: '4차전 우천취소, 역대 가장 늦은 KS 가능성 높아져',
    commentCount: 32,
    writer: '오늘도너를',
    views: 3123,
    date: '11-08',
  },
  {
    likes: 153,
    title: '한대화 감독관 우취 결정 이유 "비 예보 有, 해 안 떠 정비 쉽지 않다" [KS4]',
    commentCount: 32,
    writer: '오늘도너를',
    views: 3123,
    date: '11-08',
  },
  {
    likes: 63,
    title: '여호와의 증인은 "양심적 납세 거부"도 가능할까?',
    commentCount: 32,
    writer: '오늘도너를',
    views: 3123,
    date: '11-08',
  },
  {
    likes: 2,
    title: '2층 열린 문으로 찾아온 "불청객"…카페·패스트푸드점 "속앓이"',
    commentCount: 32,
    writer: '오늘도너를',
    views: 3123,
    date: '11-08',
  },
  {
    likes: 1,
    title: '정부 "LPG차 사용제한 폐지"…일반인 구매 길 열린다',
    commentCount: 32,
    writer: '오늘도너를',
    views: 3123,
    date: '11-08',
  },
  {
    likes: 123,
    title: '얼굴 합성한 신분증으로 토익 대리 시험',
    commentCount: 32,
    writer: '오늘도너를',
    views: 3123,
    date: '11-08',
  },
];

export default data;